try:
	raise Exception()
except Exception:
	print("hello")
